### PR TITLE
Improve experience for Windows users

### PR DESCRIPTION
**Pull request by blairconrad**

### CODE REVIEW

**Comment by blairconrad** [comment]
Hey. We talked about using `cp`. I also found `rm`, but didn't discuss before adding the commit and pushing.

Supposedly I should run `make test` to test, but... no make!

**Review by pawamoy — APPROVED** [review]
Thanks! Looking good :slightly_smiling_face:

**Comment by blairconrad** [comment]
I think test-project-ci is stuck. Perhaps because it's run from a PR and [I have no GH_TOKEN](https://github.com/pawamoy/copier-uv/actions/runs/11516663377/job/32060904787?pr=33#step:7:2096)?

**Comment by pawamoy** [comment]
Huh, weird, I thought it would be using my own CI and therefore the token would be set?

**Comment by pawamoy** [comment]
Anyway, I canceled the workflow. Merging!

**Comment by blairconrad** [comment]
> Huh, weird, I thought it would be using my own CI and therefore the token would be set?

I think there are barriers in place for security. Letting my (not-yet-merged) code use your GH_TOKEN is danger!

**Comment by pawamoy** [comment]
Ha, yeah, makes sense indeed!

**Pull request merged**
